import { Tokens } from "@pandacss/types"

export const sizes: Tokens["sizes"] = {
  "2xs": { value: "2px" },
  xs: { value: "4px" },
  sm: { value: "8px" },
  md: { value: "12px" },
  lg: { value: "16px" },
  xl: { value: "24px" },
  "2xl": { value: "32px" },
  "3xl": { value: "40px" },
  "4xl": { value: "48px" },
  "5xl": { value: "56px" },
  "6xl": { value: "64px" },
  "7xl": { value: "72px" },
  "8xl": { value: "80px" },
  "9xl": { value: "88px" },
  "10xl": { value: "96px" },
  "11xl": { value: "104px" },
  "12xl": { value: "112px" },
  "100%": { value: "100%" },
  min: { value: "min-content" },
  max: { value: "max-content" },
  fit: { value: "fit-content" },
}
