export const BASE_URL = 'http://image.tmdb.org/t/p/'
export const SECURE_BASE_URL = 'https://image.tmdb.org/t/p/'

export type BackdropSizes = 'w300' 
  | 'w780' 
  | 'w1280' 
  | 'original'

export type LogoSizes = 'w45' 
  | 'w92' 
  | 'w154' 
  | 'w185' 
  | 'w300' 
  | 'w500' 
  | 'original'

export type PosterSizes = 'w92' 
  | 'w154' 
  | 'w185' 
  | 'w342' 
  | 'w500' 
  | 'w780' 
  | 'original'

export type ProfileSizes = 'w45'
  | 'w185'
  | 'h632'
  | 'original'

export type StillSizes = 'w92'
  | 'w185'
  | 'w300'
  | 'original'

export type ChangeKeys = 'adult' 
  | 'air_date' 
  | 'also_known_as' 
  | 'alternative_titles' 
  | 'biography' 
  | 'birthday' 
  | 'budget' 
  | 'cast' 
  | 'certifications' 
  | 'character_names' 
  | 'created_by' 
  | 'crew' 
  | 'deathday' 
  | 'episode' 
  | 'episode_number' 
  | 'episode_run_time' 
  | 'freebase_id' 
  | 'freebase_mid' 
  | 'general' 
  | 'genres' 
  | 'guest_stars' 
  | 'homepage' 
  | 'images' 
  | 'imdb_id' 
  | 'languages' 
  | 'name' 
  | 'network' 
  | 'origin_country' 
  | 'original_name' 
  | 'original_title' 
  | 'overview' 
  | 'parts' 
  | 'place_of_birth' 
  | 'plot_keywords' 
  | 'production_code' 
  | 'production_companies' 
  | 'production_countries' 
  | 'releases' 
  | 'revenue' 
  | 'runtime' 
  | 'season' 
  | 'season_number' 
  | 'season_regular' 
  | 'spoken_languages' 
  | 'status' 
  | 'tagline' 
  | 'title' 
  | 'translations' 
  | 'tvdb_id' 
  | 'tvrage_id' 
  | 'type' 
  | 'video' 
  | 'videos'