"use client"

import { Grid } from "@nextui-org/react"
import type { GetStaticProps, NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { useContext, useEffect, useState } from "react"
import { SearchContext } from "../context/SearchContext"
import { ApiResponse, TvListResultObject } from "../interface"
import styles from "../styles/Home.module.css"
import debounce from "lodash/debounce"
import { getImagePath, getJson } from "../utils"
import { MovieCard } from "../components/MovieCard/MovieCard"
import * as S from "./styles"

interface HomeProps {
  shows: TvListResultObject[]
}

const Home: NextPage<HomeProps> = () => {
  const [searchResults, setSearchResults] = useState<TvListResultObject[]>([])
  const { query } = useContext(SearchContext)

  useEffect(() => {
    getJson<ApiResponse<TvListResultObject>>(`api/search/popular`)
      .then((res) => {
        setSearchResults(res.results)
      })
      .catch(console.error)
  }, [])

  useEffect(() => {
    if (query) {
      debounce(() => {
        getJson<ApiResponse<TvListResultObject>>(`api/search/${query}`).then(
          (res) => {
            setSearchResults(res.results)
          }
        )
      }, 3000)()
    }
  }, [query])

  return (
    <div className={styles.container}>
      <Head>
        <title>Trending :: flexflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <S.MainContainer>
          <S.MainGrid>
            {searchResults.map((show) => (
              <S.MainGridItem key={show.id}>
                <Link
                  passHref
                  href={`/show/${encodeURIComponent(show.id)}`}
                  style={{ width: "100%" }}
                >
                  <MovieCard
                    title={show.first_air_date}
                    subtitle={show.name}
                    imgSrc={show.poster_path}
                  />
                </Link>
              </S.MainGridItem>
            ))}
          </S.MainGrid>
        </S.MainContainer>
      </main>
    </div>
  )
}

export default Home
