const data = [
    {
        title: 'Game of Thrones',
        tv_station: 'HBO',
        duration: 57,
        image: 'game-of-thrones.jpeg',
        actors: ['Emilia Clarke', 'Kit Harington', 'Sophie Turner', 'Peter Dinklage', 'Lena Headey', 'Pedro Pascal'],
        type: ['Action', 'Adventure', 'Drama'],
        plot: 'Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.',
        episodes: 73,
        tags: ['dragons', 'winterfell', 'the wall', 'hodor', 'white', 'walkers', 'westeros', 'fantasy'],
        likes: 0,
        startYear: 2011,
        endYear: 2019
    },
    {
        title: 'Breaking Bad',
        tv_station: 'AMC',
        duration: 49,
        image: 'breaking-bad.jpg',
        actors: ['Bryan Cranston', 'Aaron Paul', 'Bob Odenkirk', 'Giancarlo Esposito', 'Jonathan Banks'],
        type: ['Crime', 'Thriller', 'Drama'],
        plot: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his familys future.',
        episodes: 62,
        tags: ['crystal', 'meth', 'mexico', 'albuquerque', 'heisenberg', 'los', 'pollos', 'hermanos'],
        likes: 0,
        startYear: 2008,
        endYear: 2013
    },
    {
        title: 'Better Call Saul',
        tv_station: 'AMC',
        duration: 46,
        image: 'better-call-saul.jpg',
        actors: ['Bob Odenkirk', 'Giancarlo Esposito', 'Jonathan Banks', 'Rhea Seehorn', 'Patrick Fabian'],
        type: ['Crime', 'Drama'],
        plot: 'The trials and tribulations of criminal lawyer Jimmy McGill in the time before he established his strip-mall law office in Albuquerque, New Mexico.',
        episodes: 40,
        tags: ['albuquerque', 'lawyer', 'sandpiper', 'jimmy', 'mcgill'],
        likes: 0,
        startYear: 2015,
        endYear: null
    },
    {
        title: 'Mr. Robot',
        tv_station: 'USA Network',
        duration: 49,
        image: 'mr-robot.jpg',
        actors: ['Rami Malek', 'Christian Slater', 'Carly Chaikin', 'Martin Wallström'],
        type: ['Crime', 'Drama', 'Thriller'],
        plot: 'Elliot, a brilliant but highly unstable young cyber-security engineer and vigilante hacker, becomes a key figure in a complex game of global dominance when he and his shadowy allies try to take down the corrupt corporation he works for.',
        episodes: 42,
        tags: ['hacking', 'drugs', 'allsafe', 'cyber-security', 'viligante', 'corruption'],
        likes: 0,
        startYear: 2015,
        endYear: null
    },
    {
        title: 'The Walking Dead',
        tv_station: 'AMC',
        duration: 44,
        image: 'the-walking-dead.jpg',
        actors: ['Norman Reedus', 'Andrew Lincoln', 'Jon Bernthal', 'Melissa McBride', 'Jeffrey Dean Morgan'],
        type: ['Drama', 'Horror', 'Thriller'],
        plot: 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins, and must lead a group of survivors to stay alive.',
        episodes: 139,
        tags: ['zombies', 'apocalypse', 'survivors', 'sanctuary'],
        likes: 0,
        startYear: 2010,
        endYear: null
    },
    {
        title: 'The Punisher',
        tv_station: 'Netflix',
        duration: 53,
        image: 'the-punisher.jpg',
        actors: ['Jon Bernthal', 'Ben Barnes', 'Amber Rose Revah', 'Jason R. Moore'],
        type: ['Action', 'Adventure', 'Crime'],
        plot: 'After the murder of his family, Marine veteran Frank Castle becomes the vigilante known as The Punisher with only one goal in mind: to avenge them.',
        episodes: 26,
        tags: ['frank', 'castle', 'marine', 'veteran', 'vigilante', 'marvel'],
        likes: 0,
        startYear: 2017,
        endYear: 2019
    },
    {
        title: 'Daredevil',
        tv_station: 'Netflix',
        duration: 54,
        image: 'daredevil.jpg',
        actors: ['Charlie Cox', 'Deborah Ann Woll', 'Elden Henson', 'Vincent D Onofrio'],
        type: ['Action', 'Drama', 'Crime'],
        plot: 'A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.',
        episodes: 39,
        tags: ['frank', 'castle', 'marvel', 'new', 'york', 'marvel'],
        likes: 0,
        startYear: 2015,
        endYear: 2018
    },
    {
        title: 'True Detective',
        tv_station: 'HBO',
        duration: 55,
        image: 'true-detective.jpg',
        actors: ['Matthew McConaughey', 'Colin Farrell', 'Mahershala Ali', 'Woody Harrelson', 'Rachel McAdams', 'Vince Vaughn'],
        type: ['Mystery', 'Drama', 'Crime'],
        plot: 'Seasonal anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.',
        episodes: 24,
        tags: ['police', 'investigations', 'secrets', 'occult'],
        likes: 0,
        startYear: 2014,
        endYear: null
    },
    {
        title: 'Stranger Things',
        tv_station: 'Netflix',
        duration: 51,
        image: 'stranger-things.jpg',
        actors: ['Winona Ryder', 'Finn Wolfhard', 'Millie Bobby Brown', 'Caleb McLaughlin'],
        type: ['Fantasy', 'Drama', 'Horror'],
        plot: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
        episodes: 33,
        tags: ['supernatural', 'synthwave', 'retro', 'eleven', 'aliens'],
        likes: 0,
        startYear: 2016,
        endYear: null
    },
    {
        title: 'Chernobyl',
        tv_station: 'HBO',
        duration: 330,
        image: 'chernobyl.jpg',
        actors: ['Jessie Buckley', 'Jared Harris', 'Stellan Skarsgård', 'Paul Ritter '],
        type: ['Thriller', 'Drama', 'History'],
        plot: 'In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the worlds worst man-made catastrophes.',
        episodes: 5,
        tags: ['disaster', 'nuclear', 'documentary', 'ukraine', 'aliens'],
        likes: 0,
        startYear: 2019,
        endYear: 2019
    },
    {
        title: 'Supernatural',
        tv_station: 'The CW',
        duration: 44,
        image: 'supernatural.jpg',
        actors: ['Jared Padalecki', 'Jensen Ackles', 'Jeffrey Dean Morgan'],
        type: ['Drama', 'Fantasy', 'Horror'],
        plot: 'Two brothers follow their fathers footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.',
        episodes: 314,
        tags: ['supernatural', 'winchester', 'sam', 'dean', 'demon'],
        likes: 0,
        startYear: 2005,
        endYear: null
    },
    {
        title: 'Narcos',
        tv_station: 'Netflix',
        duration: 44,
        image: 'supernatural.jpg',
        actors: ['Pedro Pascal', 'Wagner Moura', 'Boyd Holbrook', 'Alberto Ammann'],
        type: ['Biography', 'Crime', 'Drama'],
        plot: 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.',
        episodes: 30,
        tags: ['drugs', 'lord', 'cartel', 'pablo', 'escobar', 'colombia'],
        likes: 0,
        startYear: 2015,
        endYear: 2017
    },
    {
        title: 'The Mandalorian',
        tv_station: 'Disney',
        duration: 30,
        image: 'the-mandalorian.jpg',
        actors: ['Pedro Pascal', 'Carl Weathers', 'Werner Herzog', 'Nick Nolte'],
        type: ['Action', 'Adventure', 'Sci-Fi'],
        plot: 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
        episodes: 9,
        tags: ['star', 'wars', 'bounty', 'hunter', 'baby yoda', 'new republic'],
        likes: 0,
        startYear: 2019,
        endYear: null
    },
    {
        title: 'Peaky Blinders',
        tv_station: 'BBC',
        duration: 60,
        image: 'peaky-blinders.jpg',
        actors: ['Cillian Murphy', 'Paul Anderson', 'Tom Hardy', 'Helen McCrory', 'Finn Cole'],
        type: ['Crime', 'Drama'],
        plot: 'A gangster family epic set in 1919 Birmingham, England; centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.',
        episodes: 37,
        tags: ['gangsers', 'birmingham', 'horse races', 'england', 'shelby'],
        likes: 0,
        startYear: 2013,
        endYear: null
    },
    {
        title: 'Taboo',
        tv_station: 'BBC',
        duration: 59,
        image: 'taboo.jpg',
        actors: ['Tom Hardy', 'David Hayman', 'Jonathan Pryce', 'Oona Chaplin'],
        type: ['Drama', 'Mystery', 'Thriller'],
        plot: 'Adventurer James Keziah Delaney returns to London during the War of 1812 to rebuild his late fathers shipping empire. However, both the government and his biggest competitor want his inheritance at any cost - even murder.',
        episodes: 16,
        tags: ['london', 'shipping', 'empire', 'delaney'],
        likes: 0,
        startYear: 2017,
        endYear: null
    }
]

module.exports = data;